// sections.js — Définition de toutes les sections et champs du DTAO Travaux PAY
// Chaque champ inclut un `context` : le texte qui précède/entoure le champ dans le template
// `uid` : identifiant unique affiché dans l'UI et exporté en 1re colonne de l'Excel

export const SECTION_GROUPS = [
  { groupLabel: "PRÉAMBULE & RETEX", sectionIds: ["preambule_retex"] },
  { groupLabel: "PRÉAMBULE & GUIDES", sectionIds: ["identification"] },
  { groupLabel: "Modèle d'Avis d'Appel d'Offres (AAO)", sectionIds: ["aao_letter"] },
  { groupLabel: "Section II – Données Particulières de l'Appel d'Offres", sectionIds: ["prequalification", "contact", "reunion", "offre", "garanties", "remise", "evaluation"] },
  { groupLabel: "Section III – Critères d'Évaluation et de Qualification", sectionIds: ["qualification_financiere", "qualification_experience", "personnel_cle", "materiel_cle"] },
  { groupLabel: "Section IV – Formulaires de Soumission", sectionIds: ["proposition_technique", "organisation_travaux", "calendrier_execution"] },
  { groupLabel: "ESSS (transversal)", sectionIds: ["esss_guide", "esss_transverse", "esss"] },
  { groupLabel: "Section VII – Spécifications des Travaux", sectionIds: ["surete"] },
  { groupLabel: "Section IX – CCAP", sectionIds: ["ccap"] },
];

export const SECTIONS = [
  {
    id: "preambule_retex",
    title: "Préambule & RETEX",
    icon: "📖",
    description: "Note sur la révision de Février 2024 et retours d'expérience (RETEX). La section RETEX sera enrichie ultérieurement.",
    fields: [
      { uid: "PREA-000", id: "note_revision_2024", label: "Note sur la révision Février 2024", type: "readonly", ref: "Préambule",
        context: "Le présent Dossier Type d'Appel d'Offres (DTAO) intègre les évolutions de Février 2024 : nouvelle Déclaration d'Intégrité, mise à jour des règles AFD (Sections V & VI), et renforcement des exigences ESSS.",
        note: "Cette note est informative et n'est pas exportée dans le document final." },
      { uid: "PREA-RETEX", id: "retex_placeholder", label: "Retours d'expérience (RETEX)", type: "readonly", ref: "Préambule",
        context: "Espace réservé pour les retours d'expérience. Cette section sera développée ultérieurement.",
        note: "À venir." },
      { uid: "PREA-HORS-APP", id: "points_hors_app", label: "Points du DAO non pris en charge par l'application", type: "readonly", ref: "Préambule",
        context: "Liste des éléments de la rédaction du DAO qui ne sont pas automatisés et qui devront être renseignés/vérifiés manuellement dans le .docx exporté. Cette liste sera complétée ultérieurement.",
        note: "À compléter ultérieurement." },
    ],
  },
  {
    id: "identification",
    title: "Informations générales",
    icon: "📋",
    description: "Ces champs sont propagés automatiquement à chaque occurrence dans tout le document. Remplissez-les une seule fois ici.",
    fields: [
      { uid: "PREA-001", id: "date_convention", label: "Convention de Financement AFD (date de signature)", type: "select", options: ["Avant 1er Fév. 2024 → OPTION A", "À partir 1er Fév. 2024 → OPTION B"], ref: "III, V, VI",
        context: "Le contenu de la Déclaration d'Intégrité, de la Section V et de la Section VI dépend de la date de signature de la Convention de Financement de l'AFD.",
        note: "Détermine le contenu de 3 sections : Déclaration d'Intégrité, Critères d'éligibilité, Règles AFD. Le texte de l'option non retenue sera surligné en rouge dans le .docx exporté (à supprimer)." },
      { uid: "PREA-002", id: "nom_projet", label: "Nom du Projet", type: "text", placeholder: "Ex: Construction du pont de Koudougou", ref: "IS 2.1",
        context: "Projet : [insérer le nom du Projet]",
        templateBinding: { global: true, ph: ["[insérer le nom du Projet]", "[nom du Projet]", "[Nom du Projet]"], captions: ["Nom du Projet"] } },
      { uid: "PREA-003", id: "identification_travaux", label: "Identification des Travaux", type: "textarea", placeholder: "Description succincte des travaux", ref: "Page de garde",
        context: "Passation des marchés de travaux de [Insérer l'identification des Travaux]",
        templateBinding: { global: true, ph: ["[Insérer l'identification des Travaux]", "[insérer une brève description des travaux]", "[nom du Marché]"] } },
      { uid: "PREA-004-a", id: "nom_maitrise_ouvrage", label: "Nom du Maître d'Ouvrage (MOA)", type: "text", placeholder: "Ex: Ministère des Infrastructures", ref: "IS 1.1 / CCAP 1.1.2.2",
        context: "Maître d'Ouvrage : [insérer le nom du Maître d'Ouvrage]",
        templateBinding: { global: true, ph: ["[insérer le nom du Maître d'Ouvrage]", "[nom du Maître d'Ouvrage]", "[Nom du Maître d'Ouvrage]"], captions: ["Nom du Maître d'Ouvrage"] } },
      { uid: "PREA-004-a2", id: "adresse_moa", label: "Adresse du Maître d'Ouvrage (MOA)", type: "textarea", placeholder: "Adresse complète du MOA", ref: "CCAP 1.3",
        context: "L'adresse du Maître d'Ouvrage est : [insérer l'adresse du Maître d'Ouvrage]" },
      { uid: "PREA-004b", id: "nom_moe", label: "Nom du Maître d'Œuvre (MOE)", type: "text", placeholder: "Ex: Bureau d'études XYZ", ref: "CCAP 1.1.2.4",
        context: "Le nom du Maître d'Œuvre est : [insérer le nom du Maître d'Œuvre]" },
      { uid: "PREA-004c", id: "adresse_moe", label: "Adresse du Maître d'Œuvre (MOE)", type: "textarea", placeholder: "Adresse complète du MOE", ref: "CCAP 1.3",
        context: "L'adresse du Maître d'Œuvre est : [insérer l'adresse du Maître d'Œuvre]" },
      { uid: "PREA-005", id: "pays", label: "Pays", type: "text", placeholder: "Ex: Burkina Faso", ref: "Page de garde",
        context: "Pays : [insérer le pays]",
        templateBinding: { global: true, ph: ["[insérer le pays]", "[Pays]"] } },
      { uid: "PREA-006", id: "ref_aoi", label: "Référence de l'AOI", type: "text", placeholder: "Ex: AOI/2025/BF/001", ref: "IS 1.1",
        context: "AOI No : [insérer la référence]",
        templateBinding: { global: true, ph: ["[insérer la référence]", "[Référence de l'AOI]", "[référence de l'AOI]"] } },
      { uid: "PREA-007", id: "num_aao", label: "Numéro de l'Avis d'Appel d'Offres", type: "text", placeholder: "Ex: AAO-2025-001", ref: "IS 1.1",
        context: "Numéro de l'Avis d'Appel d'Offres :" },
      { uid: "PREA-008", id: "nombre_lots", label: "Nombre et identification des lots", type: "text", placeholder: "Lot unique / 3 lots", ref: "IS 1.1",
        context: "Nombre et numéro d'identification des lots faisant l'objet du présent AOI : [indiquer si non applicable]",
        // Sibling caption paragraph ends in a <w:tab/> with underscore leader;
        // strip that line so it doesn't visually compete with the filled value.
        templateBinding: { ph: "[indiquer si non applicable]", stripUnderscores: { caption: "Nombre et numéro d'identification des lots" } } },
      { uid: "PREA-009", id: "date_emission", label: "Date d'émission du DAO", type: "date", ref: "Page de garde",
        context: "Emis le : [insérer la date]",
        templateBinding: { global: true, isDate: true, ph: ["[insérer la date]", "[Date de publication de l'AAO]"] } },
    ],
  },
  {
    id: "aao_letter",
    title: "Annonce publique — Avis d'Appel d'Offres",
    icon: "📣",
    description: "Ces champs servent uniquement à la lettre publique « Modèle d'Avis d'Appel d'Offres » en début de document. Les autres informations (nom MOA, coordonnées, dates de remise/ouverture) sont dérivées automatiquement des sections Coordonnées et Remise.",
    fields: [
      { uid: "AAO-001", id: "heures_bureau", label: "Heures d'ouverture et de fermeture", type: "text", placeholder: "Ex: 8h00 – 16h00 du lundi au vendredi", ref: "AAO",
        context: "prendre connaissance des Documents d'Appel d'Offres à [adresse] de [insérer les heures d'ouverture et de fermeture]" },
      { uid: "AAO-002", id: "frais_dao_monnaie_nationale", label: "Frais DAO (monnaie nationale)", type: "text", placeholder: "Ex: 500 000 XOF", ref: "AAO",
        context: "paiement non remboursable de [insérer le montant en monnaie nationale]" },
      { uid: "AAO-003", id: "frais_dao_monnaie_convertible", label: "Frais DAO (monnaie convertible)", type: "text", placeholder: "Ex: 750 EUR", ref: "AAO",
        context: "ou [insérer le montant dans une monnaie convertible]" },
      { uid: "AAO-004", id: "conditions_qualification", label: "Liste des conditions de qualification", type: "textarea", placeholder: "Ex: capacité financière, expérience générale et spécifique, personnel clé, matériel…", ref: "AAO",
        context: "Les exigences en matière de qualifications sont : [insérer la liste des conditions d'ordre technique, financier, légal et autre(s)]" },
    ],
  },
  {
    id: "prequalification",
    title: "Pré-qualification & Procédure",
    icon: "🔍",
    description: "Choix pré-qualification / post-qualification, taille des groupements",
    fields: [
      { uid: "S02-001", id: "prequalification", label: "Pré-qualification", type: "select", options: ["est", "n'est pas"], ref: "IS 4.5",
        context: "Le présent Appel d'Offres [est / n'est pas] précédé d'une pré-qualification.",
        note: "La pré-qualification est recommandée pour les marchés de travaux importants. Si « n'est pas », la lettre aux soumissionnaires préqualifiés sera retirée du document exporté.",
        // est/n'est pas — nth=1 of three (garantie_soumission=2, declaration_garantie=3).
        templateBinding: { ph: "[est / n'est pas]", nth: 1, choice: ["est", "n'est pas"] } },
      { uid: "S02-002", id: "max_groupement", label: "Nombre max membres groupement", type: "text", placeholder: "3 ou 'sans objet'", ref: "IS 4.1",
        context: "Le nombre des membres d'un groupement sera au maximum de : [insérer un nombre maximum, par exemple trois, sinon indiquer la mention \"sans objet\"]",
        templateBinding: { ph: '[insérer un nombre maximum, par exemple trois, sinon indiquer la mention "sans objet"]' } },
    ],
  },
  {
    id: "contact",
    title: "Coordonnées & Éclaircissements",
    icon: "📬",
    description: "Adresses pour les éclaircissements",
    fields: [
      { uid: "S02-003", id: "contact_attention", label: "À l'attention de", type: "text", placeholder: "Nom du responsable", ref: "IS 7.1",
        context: "Aux seules fins d'obtention d'éclaircissements, l'adresse du Maître d'Ouvrage est la suivante : A l'attention de :" },
      { uid: "S02-004", id: "contact_adresse", label: "Adresse postale", type: "textarea", placeholder: "Adresse complète", ref: "IS 7.1",
        context: "Adresse :",
        templateBinding: { captionInline: "Adresse" } },
      { uid: "S02-005", id: "contact_tel", label: "Téléphone", type: "text", placeholder: "+XXX XX XX XX XX", ref: "IS 7.1",
        context: "Numéro de téléphone :",
        templateBinding: { captionInline: "Numéro de téléphone" } },
      { uid: "S02-006", id: "contact_email", label: "Adresse électronique", type: "text", placeholder: "email@example.com", ref: "IS 7.1",
        context: "Adresse électronique :",
        templateBinding: { captionInline: "Adresse électronique" } },
      { uid: "S02-007", id: "contact_web", label: "Page Web", type: "text", placeholder: "https://...", ref: "IS 7.1",
        context: "Adresse de la page Web :",
        templateBinding: { captionInline: "Adresse de la page Web" } },
    ],
  },
  {
    id: "reunion",
    title: "Réunion préparatoire & Visite",
    icon: "🏗️",
    description: "Réunion préparatoire et visite du site des travaux",
    fields: [
      { uid: "S02-008", id: "reunion_prevue", label: "Réunion préparatoire", type: "select", options: ["se tiendra", "n'est pas prévue"], ref: "IS 7.4",
        context: "Une réunion préparatoire [se tiendra / n'est pas prévue] à l'adresse, date et heure ci-après :",
        // Template ships two typographic variants of the same placeholder
        // (with and without spaces around the slash); both must match.
        templateBinding: { ph: ["[se tiendra / n'est pas prévue]", "[se tiendra/n'est pas prévue]"], choice: ["se tiendra", "n'est pas prévue"] } },
      { uid: "S02-009", id: "reunion_lieu", label: "Lieu", type: "text", placeholder: "Adresse", ref: "IS 7.4", condition: "reunion_prevue=se tiendra",
        context: "Lieu :",
        templateBinding: { captionInline: "Lieu" } },
      { uid: "S02-010", id: "reunion_date", label: "Date", type: "date", ref: "IS 7.4", condition: "reunion_prevue=se tiendra",
        context: "Date : [de préférence à mi-période de préparation des Offres]" },
      { uid: "S02-011", id: "reunion_heure", label: "Heure", type: "time", ref: "IS 7.4", condition: "reunion_prevue=se tiendra",
        context: "Heure :" },
      { uid: "S02-012", id: "visite_site", label: "Visite du site", type: "select", options: ["sera", "ne sera pas"], ref: "IS 7.4",
        context: "Une visite du Site des Travaux [sera / ne sera pas] organisée par le Maître d'Ouvrage.",
        // sera/ne sera pas — nth=1 of two (marge_preference=2).
        templateBinding: { ph: "[sera / ne sera pas]", nth: 1, choice: ["sera", "ne sera pas"] } },
    ],
  },
  {
    id: "offre",
    title: "Modalités de l'Offre",
    icon: "📄",
    description: "Type de prix, monnaies, validité, variantes",
    fields: [
      { uid: "S02-013", id: "type_prix", label: "Tableau des prix", type: "select", options: ["Bordereau des Prix et DQE (prix unitaires)", "Prix global et forfaitaire", "Combinaison prix unitaires + forfaitaire"], ref: "IS 11.1(b)",
        context: "Le tableau des prix suivant devra être remis avec l'Offre : [Rayer la mention inutile]",
        note: "Les options non retenues seront surlignées en rouge dans le .docx exporté." },
      { uid: "S02-014", id: "documents_additionnels", label: "Documents additionnels", type: "textarea", placeholder: "Un document par ligne (ou séparés par des virgules)", ref: "IS 11.1(i)",
        context: "Le Soumissionnaire devra joindre à son Offre les documents additionnels suivants : [insérer la liste des documents additionnels, le cas échéant]",
        note: "Les sauts de ligne (ou virgules) seront convertis en liste à puces dans le document exporté." },
      { uid: "S02-015", id: "offres_variantes", label: "Offres variantes", type: "select", options: ["sont", "ne sont pas"], ref: "IS 13.1",
        context: "Les Offres variantes [sont / ne sont pas] autorisées." },
      { uid: "S02-016", id: "variantes_techniques", label: "Variantes techniques", type: "select", options: ["sont", "ne sont pas"], ref: "IS 13.2",
        context: "Les variantes techniques [sont / ne sont pas] autorisées pour les éléments des ouvrages indiqués dans la Section VII." },
      { uid: "S02-017", id: "variantes_delais", label: "Variantes aux délais", type: "select", options: ["sont", "ne sont pas"], ref: "IS 13.5",
        context: "Des variantes aux délais d'exécution des travaux [sont / ne sont pas] autorisées.",
        note: "Si « ne sont pas », le bloc d'explication (montant d'ajustement et pénalité) sera surligné en rouge." },
      { uid: "S02-018", id: "ajustement_variante_montant", label: "Montant d'ajustement variante délai", type: "text", placeholder: "Montant et monnaie", ref: "IS 13.5", condition: "variantes_delais=sont",
        context: "Le montant d'ajustement de l'Offre pour l'évaluation sera de : [insérer montant et monnaie] par [insérer jour ou semaine]." },
      { uid: "S02-019", id: "prix_revisables", label: "Nature des prix", type: "select", options: ["révisables", "fermes"], ref: "IS 14.5",
        context: "Les prix proposés par le Soumissionnaire seront [révisables / fermes].",
        note: "Révisables recommandés si durée > 18 mois. Le guide de recommandation AFD sera toujours surligné en rouge dans le document exporté." },
      { uid: "S02-020", id: "option_monnaie", label: "Option monnaies (IS 15.1)", type: "select", options: ["Option A – Monnaie nationale uniquement", "Option B – Monnaies nationale et étrangères"], ref: "IS 15.1",
        context: "Les monnaies de l'Offre et les monnaies de règlement seront les suivantes : [Le Maître d'Ouvrage doit maintenir uniquement une des deux options]",
        note: "Option A : le Soumissionnaire est requis de libeller ses prix entièrement en monnaie nationale. Option B : le Soumissionnaire est autorisé à libeller directement ses prix en monnaies nationale et étrangères. Le texte de l'option non retenue sera surligné en rouge dans le document exporté." },
      { uid: "S02-021", id: "monnaie_nationale", label: "Monnaie nationale", type: "text", placeholder: "Franc CFA (XOF)", ref: "IS 15.1",
        context: "les prix seront entièrement libellés en ____________, la monnaie du pays du Maître d'Ouvrage" },
      { uid: "S02-022", id: "validite_offre", label: "Validité de l'Offre (jours)", type: "text", placeholder: "90 à 120", ref: "IS 18.1",
        context: "La Période de validité de l'Offre sera de _____________________ [insérer nombre entre 90 et 120] jours." },
      { uid: "S02-023", id: "actualisation_prix", label: "Formule d'actualisation (prix fermes)", type: "text", placeholder: "Formule ou coefficient", ref: "IS 18.3(a)", condition: "prix_revisables=fermes",
        context: "Le Montant du Marché sera le Montant de l'Offre actualisé de la manière suivante : [insérer formule ou \"selon un coefficient d'actualisation\"]" },
    ],
  },
  {
    id: "garanties",
    title: "Garanties de Soumission",
    icon: "🔒",
    description: "Garantie ou Déclaration de Garantie de Soumission",
    fields: [
      { uid: "S02-024", id: "garantie_soumission", label: "Garantie de Soumission", type: "select", options: ["est", "n'est pas"], ref: "IS 19.1",
        context: "Une Garantie de Soumission [est / n'est pas] requise.",
        note: "Si « n'est pas », les champs ci-dessous restent exportés (valeur « non-applicable ») et les blocs d'explication seront surlignés en rouge dans le document.",
        // est/n'est pas — nth=2 of three (prequalification=1, declaration_garantie=3).
        templateBinding: { ph: "[est / n'est pas]", nth: 2, choice: ["est", "n'est pas"] } },
      { uid: "S02-025", id: "declaration_garantie", label: "Déclaration de Garantie", type: "select", options: ["est", "n'est pas"], ref: "IS 19.1",
        context: "Une Déclaration de Garantie de Soumission [est / n'est pas] requise.",
        note: "Garantie et Déclaration sont mutuellement exclusives.",
        // est/n'est pas — nth=3 of three. Template: "Déclaration de Garantie de
        // Soumission ____________ [est / n'est pas] requise." — strip the 12
        // leading underscores after the substitution.
        templateBinding: { ph: "[est / n'est pas]", nth: 3, choice: ["est", "n'est pas"], stripUnderscores: true } },
      { uid: "S02-026", id: "montant_garantie", label: "Montant de la Garantie", type: "text", placeholder: "50 000 000 XOF", ref: "IS 19.1",
        condition: "garantie_soumission=est",
        context: "Son montant est de : [insérer montant entre 1% et 3% de l'estimation du Montant du Marché et préciser la monnaie].",
        note: "Inactif si « Garantie de Soumission n'est pas requise » — exporté automatiquement en « non-applicable »." },
      { uid: "S02-027", id: "garantie_lots_multi", label: "Garantie par lots (multi-lots)", type: "textarea", placeholder: "Montants et monnaies par lot…", ref: "IS 19.1",
        context: "[Lorsqu'il y a plus d'un lot, insérer le montant et la monnaie de la Garantie de Soumission requise par lot.]",
        note: "À renseigner uniquement si plusieurs lots. Sinon laisser vide (exporté en « non-applicable »)." },
      { uid: "S02-028", id: "autres_garanties", label: "Autres garanties acceptables", type: "text", placeholder: "Néant", ref: "IS 19.3(d)",
        context: "Autres types de garanties acceptables : [indiquer \"Néant\" si pas applicable]" },
      { uid: "S02-029", id: "exclusion_annees", label: "Durée d'exclusion (années)", type: "text", placeholder: "2", ref: "IS 19.9", condition: "declaration_garantie=est",
        context: "le Maître d'Ouvrage l'exclura de toute attribution de marché(s) pour une période de _________________ [insérer le nombre d'années] ans." },
    ],
  },
  {
    id: "remise",
    title: "Remise & Ouverture des Offres",
    icon: "📦",
    description: "Adresses, dates limites et ouverture des plis",
    fields: [
      { uid: "S02-030", id: "copies_offre", label: "Nombre de copies papier", type: "text", placeholder: "3", ref: "IS 20.1",
        context: "Outre l'original de l'Offre, le nombre de copies demandé est de : [insérer le nombre] copies papier et une (1) copie numérique.",
        templateBinding: { ph: "[insérer le nombre]", nth: 1 } },
      { uid: "S02-031", id: "habilitation", label: "Habilitation du signataire", type: "text", placeholder: "Pouvoir de l'autorité compétente...", ref: "IS 20.2",
        context: "La confirmation écrite de l'habilitation du signataire à engager le Soumissionnaire consistera en : [insérer]" },
      { uid: "S02-032", id: "remise_attention", label: "Remise – À l'attention de", type: "text", ref: "IS 22.1",
        context: "Aux seules fins de remise des Offres, l'adresse du Maître d'Ouvrage est la suivante : A l'attention de :" },
      { uid: "S02-033", id: "remise_adresse", label: "Adresse de remise", type: "textarea", ref: "IS 22.1",
        context: "Adresse complète :" },
      { uid: "S02-034", id: "date_limite", label: "Date limite de remise", type: "date", ref: "IS 22.1",
        context: "La date et heure limites de remise des Offres sont les suivantes : Date :" },
      { uid: "S02-035", id: "heure_limite", label: "Heure limite", type: "time", ref: "IS 22.1",
        context: "Heure :" },
      { uid: "S02-036", id: "ouverture_adresse", label: "Adresse d'ouverture des plis", type: "textarea", ref: "IS 25.1",
        context: "L'ouverture des plis aura lieu à l'adresse suivante : Adresse complète :" },
      { uid: "S02-037", id: "ouverture_date", label: "Date d'ouverture", type: "date", ref: "IS 25.1",
        context: "Date :" },
      { uid: "S02-038", id: "ouverture_heure", label: "Heure d'ouverture", type: "time", ref: "IS 25.1",
        context: "Heure :" },
    ],
  },
  {
    id: "evaluation",
    title: "Évaluation & Conversion",
    icon: "⚖️",
    description: "Monnaie d'évaluation, préférence nationale, sous-traitance",
    fields: [
      { uid: "S02-039", id: "monnaie_evaluation", label: "Monnaie d'évaluation", type: "text", placeholder: "Monnaie nationale", ref: "IS 32.1",
        context: "La monnaie utilisée pour convertir en une seule monnaie est : [Insérer la monnaie, normalement la monnaie nationale]" },
      { uid: "S02-040", id: "source_taux_change", label: "Source taux de change", type: "text", placeholder: "Banque Centrale", ref: "IS 32.1",
        context: "La source du taux de change à employer est : [habituellement la banque centrale du pays]" },
      { uid: "S02-041", id: "option_conversion", label: "Option de conversion (IS 32.1)", type: "select", options: ["A", "B"], ref: "IS 32.1",
        context: "La(es) monnaie(s) sera(ont) convertie(s) conformément à l'Option [A / B]",
        note: "Le bloc de l'option non retenue sera surligné en rouge dans le document exporté." },
      { uid: "S02-042", id: "marge_preference", label: "Marge de préférence", type: "select", options: ["sera", "ne sera pas"], ref: "IS 33.1",
        context: "Une marge de préférence [sera / ne sera pas] accordée aux entreprises nationales.",
        note: "Uniquement si réglementation locale l'exige + accord AFD. Les guides AFD seront toujours surlignés en rouge.",
        // sera/ne sera pas — nth=2 of two (visite_site=1).
        templateBinding: { ph: "[sera / ne sera pas]", nth: 2, choice: ["sera", "ne sera pas"] } },
      { uid: "S02-043", id: "sous_traitants_designes", label: "Sous-traitants désignés", type: "select", options: ["prévoit", "ne prévoit pas"], ref: "IS 34.1",
        context: "Le Maître d'Ouvrage [prévoit / ne prévoit pas] de faire réaliser certaines parties par des sous-traitants désignés." },
    ],
  },
  {
    id: "qualification_financiere",
    title: "Qualification Financière",
    icon: "💰",
    description: "Capacité financière et chiffre d'affaires minimum",
    fields: [
      { uid: "S03-001", id: "capacite_financiere", label: "Trésorerie exigée (€)", type: "text", placeholder: "3-4 mois facturation", ref: "III – 3.1",
        context: "Le Soumissionnaire doit démontrer qu'il dispose [...] à hauteur de [insérer le montant en € correspondant au montant de trois à quatre mois de facturation de travaux pour le marché]",
        note: "3 à 4 mois de facturation des travaux." },
      { uid: "S03-002", id: "ca_minimum", label: "CA annuel moyen min. (€)", type: "text", placeholder: "1,5-2× facturation annuelle", ref: "III – 3.2",
        context: "Avoir un chiffre d'affaires annuel moyen d'au moins ________ [insérer montant en équivalent € en toutes lettres et en chiffres]" },
      { uid: "S03-003", id: "ca_periode", label: "Années pour le CA", type: "text", placeholder: "5 (min. 3)", ref: "III – 3.2",
        context: "sur les ______ [insérer le nombre d'années, généralement 5 ans et au minimum 3 ans] dernières années." },
      { uid: "S03-002b", id: "ca_membre_pct_lettres", label: "% Chaque membre — en lettres", type: "text", placeholder: "vingt-cinq", ref: "III – 3.2",
        context: "Doit satisfaire à [vingt-cinq] pour cent [25%] de la condition requise (colonne « Chaque membre » du Groupement d'entreprises)" },
      { uid: "S03-002c", id: "ca_membre_pct_chiffre", label: "% Chaque membre — en chiffres", type: "text", placeholder: "25", ref: "III – 3.2",
        context: "Doit satisfaire à [vingt-cinq] pour cent [25%] de la condition requise — chiffre uniquement, le « % » est ajouté automatiquement" },
      { uid: "S03-002d", id: "ca_unique_pct_lettres", label: "% Un membre — en lettres", type: "text", placeholder: "quarante", ref: "III – 3.2",
        context: "Doit satisfaire à [quarante] pour cent [40%] de la condition requise (colonne « Un membre » du Groupement d'entreprises)" },
      { uid: "S03-002e", id: "ca_unique_pct_chiffre", label: "% Un membre — en chiffres", type: "text", placeholder: "40", ref: "III – 3.2",
        context: "Doit satisfaire à [quarante] pour cent [40%] de la condition requise — chiffre uniquement, le « % » est ajouté automatiquement" },
    ],
  },
  {
    id: "qualification_experience",
    title: "Critères d'Expérience",
    icon: "🏢",
    description: "Expérience générale et spécifique de construction",
    fields: [
      { uid: "S03-004", id: "exp_generale_annees", label: "Expérience générale (années)", type: "text", placeholder: "5 (min 3)", ref: "III – 4.1",
        context: "Expérience de marchés de construction [...] au cours des [insérer le nombre d'années, généralement 5 ans et au minimum 3 ans] dernières années" },
      { uid: "S03-005", id: "exp_generale_annee_depart", label: "Année de début", type: "text", placeholder: "2020", ref: "III – 4.1",
        context: "à partir du 1er janvier de l'année _______ [insérer l'année]" },
      { uid: "S03-006", id: "exp_specifique_n", label: "Nombre marchés similaires (N)", type: "text", placeholder: "2", ref: "III – 4.2(a)",
        context: "Participation [...] dans N marchés, d'un montant minimum de V [insérer des valeurs pour N, normalement deux, et V] chacun." },
      { uid: "S03-007", id: "exp_specifique_v", label: "Montant min. par marché (V, €)", type: "text", placeholder: "En €", ref: "III – 4.2(a)",
        context: "d'un montant minimum de V [insérer la valeur de V]" },
      { uid: "S03-008", id: "exp_specifique_annee", label: "Année début référence", type: "text", placeholder: "5-10 ans", ref: "III – 4.2(a)",
        context: "exécutés à compter du 1er janvier [insérer l'année, la période à considérer est généralement de 5 à 10 ans]" },
      { uid: "S03-009", id: "exp_activites_cles", label: "Activités clés (4.2b)", type: "textarea", placeholder: "Activités, volumes, taux de production...", ref: "III – 4.2(b)",
        context: "une expérience minimale de construction achevée de manière satisfaisante dans les domaines suivants [fournir la liste des activités en indiquant le volume, le nombre ou le taux de production tel qu'applicable]" },
      { uid: "S03-009b", id: "exp_activites_un_membre", label: "Activités clés — colonne « Un membre »", type: "textarea", placeholder: "Liste des activités et minima requis...", ref: "III – 4.2(b)",
        context: "Doit satisfaire à la condition requise dans les domaines mentionnés ci-après : [fournir la liste des activités en indiquant le minimum requis]" },
      { uid: "S03-009c", id: "sst_specialise_autorise", label: "Sous-traitant spécialisé", type: "toggle", ref: "III – 4.2(b)(ii)",
        context: "Le Maître d'Ouvrage autorise des travaux spécialisés ?",
        notes: [
          "Si « Oui », un champ apparaît pour décrire la nature des travaux spécialisés. Si « Non », toute la ligne 4.2(b)(ii) du tableau est surlignée rouge à l'export pour suppression par le MOA."
        ] },
      { uid: "S03-009d", id: "sst_specialise_description", label: "Description des travaux spécialisés", type: "textarea", placeholder: "Nature et caractéristiques des travaux spécialisés autorisés en sous-traitance...", ref: "III – 4.2(b)(ii)",
        context: "[ajouter le critère suivant si un sous-traitant spécialisé est autorisé et décrire la nature et les caractéristiques des travaux spécialisés]",
        condition: "sst_specialise_autorise=Oui" },
    ],
  },
  {
    id: "personnel_cle",
    title: "Personnel clé",
    icon: "👷",
    description: "Postes clés, années d'expérience générale et comparable",
    fields: [
      { uid: "S03-010", id: "personnel_table", label: "Tableau du personnel clé", type: "personnel_table", ref: "III – 1.5",
        context: "Le Soumissionnaire démontrera qu'il dispose d'un personnel répondant aux critères ci-après pour les postes clés suivants :",
        defaultRows: [
          { poste: "Expert Environnemental et Social", exp_generale: "5", exp_comparable: "2", note: "Si les travaux présentent des risques élevés et/ou ont un impact E&S significatif" },
          { poste: "Expert Santé et Sécurité", exp_generale: "5", exp_comparable: "2", note: "Si les travaux présentent des risques élevés et/ou ont un impact S&S significatif" },
        ]
      },
    ],
  },
  {
    id: "materiel_cle",
    title: "Matériel clé",
    icon: "🚜",
    description: "Matériel clé requis et quantités minimales",
    fields: [
      { uid: "S03-011", id: "materiel_table", label: "Tableau du matériel clé", type: "materiel_table", ref: "III – Matériel",
        context: "Le Soumissionnaire démontrera qu'il peut se procurer le matériel clé suivant pour les travaux :",
        defaultRows: []
      },
    ],
  },
  {
    id: "esss_guide",
    title: "Guide ESSS",
    icon: "📖",
    description: "Guide sur les Critères Environnementaux, Sociaux, Santé et Sécurité (ESSS) du DAO Travaux.",
    fields: [
      { uid: "ESSS-GUIDE-01", id: "esss_guide_intro", label: "Contexte ESSS", type: "readonly", ref: "Guide",
        context: "Lorsque le Projet a été jugé à fort impact environnemental et/ou social, en général, une étude d'impact E&S (EIES) a été conduite et un Plan de Gestion E&S (PGES) pour le Projet a été établi. L'EIES met en évidence des risques et impacts importants E&S et le PGES propose des mesures d'atténuation à mettre en œuvre. Certaines de ces mesures, mais pas toutes, concernent les travaux du Projet (voir schéma ci-dessous). Les mesures à prendre en compte dans les travaux peuvent être de deux types : d'une part, les mesures qui conduisent à une modification de la conception de l'ouvrage permanent et qui induisent une modification des spécifications techniques et des plans de l'ouvrage permanent ; d'autre part, des mesures et précautions à prendre dans le cadre de la gestion du Chantier. Ce sont ces dernières mesures que les Spécifications Environnementales, Sociales, Santé et Sécurité (ESSS) au présent DAO spécifient, même en cas d'absence de PGES." },
      { uid: "ESSS-GUIDE-02", id: "esss_guide_schema", label: "Schéma : impact des études E&S sur le DAO Travaux", type: "readonly", ref: "Guide",
        imageSrc: "/guide-esss-schema.png",
        imageAlt: "Schéma EIES → PGES → Conception / Mesures MOA / Phase construction / Phase exploitation, avec impact sur le DAO Travaux." },
      { uid: "ESSS-GUIDE-03", id: "esss_guide_ajustement", label: "Ajustement du DAO en fonction des documents ESSS", type: "readonly", ref: "Guide",
        context: "Le présent DAO doit être ajusté en tenant compte des documents ESSS disponibles (étude d'impact ESSS, PGES, PAR, PEES, etc.) et de la règlementation applicable à la maîtrise d'ouvrage." },
      { uid: "ESSS-GUIDE-04", id: "esss_guide_tableau", label: "Étapes de passation et points de vérification", type: "readonly", ref: "Guide",
        context: "Le tableau ci-dessous indique les éléments à ajuster et les points de vérification, aux différentes étapes de la passation du marché puis de son exécution." },
    ],
  },
  {
    id: "esss_transverse",
    title: "Dispositions ESSS",
    icon: "🌿",
    description: "Spécifications ESSS transversales (CCAP 1.1.6.11 · Section VII). Applicabilité, enjeux, exigences et articles non applicables.",
    fields: [
      { uid: "S-ESSS-01", id: "esss_applicable", label: "Spécifications ESSS", type: "toggle", ref: "CCAP 1.1.6.11",
        context: "Les spécifications ESSS sont-elles applicables ? (en lien avec CCAP — Partie A 1.1.6.11)",
        notes: [
          "Dans le cas de travaux pour lesquels la gestion du Chantier et de la zone d'activités ne présente que des impacts ESSS mineurs, ces Spécifications ESSS peuvent être rendues non applicables à la clause 1.1.6.11 du CCAP, en cochant « Non » à la case correspondante, et supprimées des Documents d'Appels d'Offres.",
          "Un accord de l'AFD est requis pour cocher « Non ». Les Spécifications ESSS ne sont pas applicables pour des travaux à faible impact et risque environnemental, social, santé ou sécurité.",
        ],
        recommendation: {
          title: "Cas d'application des Spécifications ESSS",
          text: "Cette Sous-Clause n'est à modifier que lorsque les Spécifications ESSS ne sont pas applicables.\n\n3 cas de figure peuvent conduire à la non-inclusion des Spécifications ESSS :\n• faible montant estimatif des travaux (≤ 3 M EUR) ;\n• faibles risques et impacts ESSS des travaux (chantier de forages, installation d'équipement, en cas d'une faible composante de génie civil, etc.) ;\n• cofinancement.\n\nSi les spécifications sont rendues non applicables, alors la méthodologie ESSS, le bordereau des prix ESSS et les clauses ESSS du CCAP du Marché ne s'appliqueront pas non plus."
        } },
      { uid: "S-ESSS-02", id: "enjeux_esss", label: "Enjeux ESSS", type: "enjeux_list", ref: "Section VII",
        context: "Les sujets ESSS identifiés lors l'étude d'impact environnementale et sociale du projet comme présentant un risque majeur pour la gestion du Chantier sont :",
        condition: "esss_applicable=Oui",
        recommendation: {
          title: "Sélection des enjeux ESSS",
          text: "Il est nécessaire de sélectionner les sujets ESSS les plus sensibles en fonction des enjeux et impacts les plus importants identifiés en matière ESSS, et sur lesquels le Soumissionnaire devra produire une méthodologie ESSS détaillée dans son offre technique, expliquant comment il entend respecter les exigences des Spécifications ESSS sur ces différents points.\n\nNormalement, la liste devrait être réduite à environ 3 à 5 sujets. Cette liste devrait être similaire à celle indiquée au critère de qualification 5.2. Le choix de ces items doit provenir des enjeux ESSS de gestion de Chantier identifiés dans les études d'impact ESSS et dans le PGES.\n\nUne liste trop longue risque de conduire à la transmission de méthodologies génériques par les entreprises (sans qu'elles soient adaptées aux caractéristiques du Chantier)."
        } },
      { uid: "S-ESSS-03", id: "exigences_esss", label: "Exigences ESSS", type: "toggle", ref: "Section VII",
        context: "Les normes, standards et seuils préconisés en matières ESSS par les institutions spécialisées internationales affiliées aux Nations Unies s'appliquent au Marché :",
        condition: "esss_applicable=Oui",
        notes: [
          "En cas de projet classé B par l'AFD, cocher « Non ». Seule la réglementation du pays est applicable. Il convient donc de compléter le tableau ci-après, conformément à l'exemple fourni, en indiquant que les Articles 9.2 et 9.3 ne s'appliquent pas. En cas de projet classé A ou B+, il convient de cocher « Oui ».",
          "Le classement A, B+ ou B du projet est effectué par la Division AES (Appui Environnemental et Social) de l'AFD, après analyse des risques et impact Environnemental et Social du projet.",
        ] },
      { uid: "S-ESSS-04", id: "articles_non_applicables", label: "Exigences ESSS non applicables", type: "articles_table", ref: "Section VII",
        context: "Les Articles suivants des Spécifications ESSS ne s'appliqueront pas dans le cadre de ce Marché et ne seront donc pas chiffrés par le Soumissionnaire dans le tableau spécifique des Prix ESSS :",
        condition: "esss_applicable=Oui",
        recommendation: {
          title: "Ajustement des Spécifications ESSS",
          text: "Si nécessaire (au regard de la table des matières), ajustement des spécifications standard ESSS en fonction des enjeux et impacts identifiés en matière ESSS et en fonction de la règlementation applicable (si celle-ci est plus exigeante).\n\nIl peut s'agir d'inclure des spécifications sur des sujets spécifiques qui ne sont pas couverts par les spécifications standard (par exemple, protection de récifs coralliens ou mesures de protection en cas d'utilisation d'explosifs).\n\nIl convient également de rendre non-applicables des spécifications qui ne seraient pas pertinentes par rapport au type de travaux et au contexte du Chantier (cf. tableau à remplir).\n\nUn exemple est donné, à titre indicatif."
        } },
    ],
  },
  {
    id: "esss",
    title: "Critères ESSS",
    icon: "🌿",
    description: "Environnement, Social, Santé et Sécurité — critères de qualification 5.1 à 5.4",
    fields: [
      { uid: "S03-ESSS-REDIR", id: "esss_redirect", label: "Voir la section « ESSS »", type: "readonly", ref: "Transversal",
        context: "Les champs ESSS (Spécifications applicables, Enjeux, Exigences, Articles non applicables) sont centralisés dans la section transversale « ESSS » du menu de gauche." },
      { uid: "S03-ESSS-IMPACTS-MINEURS", id: "esss_impacts_mineurs", label: "Impacts ESSS de la gestion du chantier mineurs ?", type: "toggle", ref: "Transversal",
        context: "Les impacts ESSS de la gestion du chantier sont-ils mineurs ?",
        recommendation: {
          title: "Réduction possible des critères ESSS",
          text: "Si Oui : les critères de qualification ESSS (5.1 à 5.4) peuvent être réduits ou supprimés."
        } },
      { uid: "S03-013", id: "certifications_iso", label: "Certifications ISO", type: "multi", options: ["ISO 9001 (Qualité)", "ISO 14001 (Environnement)", "ISO 45001 (Santé & Sécurité)"], ref: "III – 5.1",
        context: "Posséder une certification ISO [...] [Sélectionner les certifications exigées en cochant la/les case(s) correspondante(s)]",
        recommendation: {
          title: "Critère 5.1 – Certification(s) ESSS",
          text: "Selon les enjeux ESSS du Chantier et le type de compétition envisagée (nationale ou internationale), il peut être décidé :\n• de ne pas garder ce critère (par exemple, AO national suffisant pour recruter une entreprise qualifiée mais les entreprises nationales n'ont pas ce type de certifications) ;\n• de ne demander qu'une partie des certifications, c'est-à-dire celle(s) correspondant à l'enjeu principal de la gestion du Chantier : enjeu environnemental (ISO 14001), enjeu de santé et sécurité (ISO 45001) ou d'organisation de chantier (ISO 9001)."
        } },
      { uid: "S03-015", id: "exp_esss_nombre", label: "Marchés ESSS requis", type: "text", placeholder: "2", ref: "III – 5.3",
        context: "Expérience de [insérer nombre, normalement deux] marchés de construction à fort enjeu ESSS",
        recommendation: {
          title: "Critère 5.3 – Expérience ESSS",
          text: "Il convient de préciser le nombre d'expériences similaires attendu et la période durant laquelle ces expériences ont dû avoir lieu. Pour cela, il convient de prendre en compte les références des entreprises connues et jugées qualifiées, afin d'adapter le nombre de référence à demander (1, 2 ou 3)."
        } },
      { uid: "S03-016", id: "exp_esss_annees", label: "Période ESSS (années)", type: "text", placeholder: "5-10", ref: "III – 5.3",
        context: "réalisés dans les [insérer nombre d'années, entre 5 et 10 ans] dernières années" },
      { uid: "S03-017", id: "transfert_competence", label: "Transfert compétence ESSS", type: "select", options: ["Oui – conserver 5.4", "Non – supprimer 5.4"], ref: "III – 5.4",
        context: "[à supprimer si le transfert de compétence n'est pas un enjeu]",
        recommendation: {
          title: "Critère 5.4 – Transfert de compétence ESSS",
          text: "Ce critère peut être supprimé si le transfert de compétence auprès d'un partenaire local ou de la main d'œuvre locale n'est pas considéré comme un enjeu pour la maîtrise d'ouvrage."
        } },
    ],
  },
  {
    id: "proposition_technique",
    title: "Formulaires Proposition Technique",
    icon: "📝",
    description: "Éléments requis dans la proposition technique du Soumissionnaire",
    fields: [
      { uid: "S04-001", id: "proposition_items", label: "Éléments de la proposition technique", type: "proposition_list", ref: "Section IV",
        context: "Le Maître d'Ouvrage indiquera, pour chacun des éléments de la proposition technique ci-après, les renseignements et détails que le Soumissionnaire devra fournir dans son Offre.",
        defaultItems: [
          { label: "Variantes techniques", enabled: true, description: "Proposition pour les éléments des ouvrages pour lesquels des variantes techniques sont autorisées" },
          { label: "Méthodologie ESSS", enabled: true, description: "Version préliminaire du PGES-Travaux conforme aux Spécifications ESSS" },
          { label: "Liste des sous-traitants", enabled: true, description: "Sous-traitants proposés avec formulaire d'engagement ESSS" },
          { label: "Organisation des travaux sur site et Méthode de réalisation", enabled: true, description: "Dispositions et méthodes, gestion coordination accès Site, aspects géotechniques" },
          { label: "Programme / Calendrier de Construction", enabled: true, description: "Programme détaillé, calendrier mobilisation, étapes clés, chemin critique" },
          { label: "Personnel proposé et CV (formulaires PER-1 et PER-2)", enabled: true, description: "Noms et CV du personnel qualifié pour les postes clés" },
          { label: "Matériel (formulaire MAT)", enabled: true, description: "Détails matériel proposé pour les équipements clés" },
        ]
      },
    ],
  },
  {
    id: "organisation_travaux",
    title: "Organisation des travaux & méthode",
    icon: "🏗️",
    description: "Aspects que le Soumissionnaire devra couvrir dans la méthode de réalisation (Section IV, formulaire « Organisation des travaux sur site et Méthode de réalisation »). Décochez les items qui ne sont pas applicables : ils seront surlignés en rouge dans le .docx exporté.",
    fields: [
      { uid: "S04-ORGA", id: "organisation_travaux_items", label: "Items « Organisation des travaux sur site »", type: "bullet_list", ref: "Section IV",
        context: "Le Soumissionnaire devra fournir tous détails sur l'organisation sur site et la méthode de réalisation des travaux indiquant comment il compte répondre aux exigences et aux objectifs du Maître d'Ouvrage. La méthode de réalisation devra au minimum couvrir les aspects suivants :",
        defaultItems: [
          { label: "Dispositions et méthodes de réalisation", enabled: true, description: "Des renseignements détaillés sur les dispositions et méthodes que le Soumissionnaire propose de mettre en œuvre pour la réalisation des travaux, suffisamment précis afin de montrer leur adéquation aux nécessités du Marché, y compris la réalisation dans le délai d'exécution indiqué." },
          { label: "Coordination de l'accès au Site", enabled: true, description: "Une description sommaire des dispositions que le Soumissionnaire propose d'adopter afin de gérer la coordination de l'accès au Site." },
          { label: "Aspects géotechniques et souterrains", enabled: true, description: "Un commentaire sur les aspects géotechniques et souterrains des travaux, y compris sur les matériaux, leurs sources et toute contrainte y afférent." },
          { label: "Aspects offshore ou côtiers", enabled: true, description: "Un commentaire sur les aspects offshore ou côtiers des travaux [selon les besoins]." },
          { label: "Logistique, transports et circulation", enabled: true, description: "Un commentaire sur la logistique et les transports et la gestion de la circulation [selon les besoins]." },
          { label: "Conformité aux Spécifications", enabled: true, description: "Une description sommaire des dispositions que le Soumissionnaire propose d'adopter afin se conformer aux Spécifications." },
          { label: "Essais de réception", enabled: true, description: "Une description sommaire des dispositions que le Soumissionnaire propose d'adopter afin de réaliser les essais de réception conformément aux Spécifications." },
          { label: "Variantes techniques autorisées", enabled: true, description: "Lorsque les variantes techniques sont autorisées pour les sections de travaux spécifiées dans la Section VII, une description complète, incluant toute la documentation nécessaire à l'évaluation, comme indiqué à l'Article 13.3 des IS, sera fournie." },
          { label: "Autre exigence (selon le besoin)", enabled: false, description: "[insérer toute autre exigence, selon le besoin]" },
        ]
      },
    ],
  },
  {
    id: "calendrier_execution",
    title: "Calendrier d'Exécution",
    icon: "📅",
    description: "Aspects que le Soumissionnaire devra couvrir dans le programme/calendrier détaillé (Section IV, formulaire « Calendrier d'Exécution »).",
    fields: [
      { uid: "S04-CAL", id: "calendrier_execution_items", label: "Items « Calendrier d'Exécution »", type: "bullet_list", ref: "Section IV",
        context: "Le Soumissionnaire devra fournir un programme détaillé et un calendrier détaillé de la mobilisation et de la réalisation des travaux à entreprendre, y compris les dates de commencement et d'achèvement pour les composantes individuelles et l'identification des étapes clés et du chemin critique. Le programme et le calendrier de réalisation sera préparé en conformité avec les Spécifications et devra au minimum couvrir les aspects suivants :",
        defaultItems: [
          { label: "Permis nécessaires au démarrage", enabled: true, description: "Des renseignements détaillés sur le calendrier pour l'obtention des permis éventuellement nécessaires pour commencer les travaux, y compris la préparation des études requises, des documents de justification et des demandes." },
          { label: "Calendrier de réalisation (Gantt, chemin critique)", enabled: true, description: "Des renseignements détaillés sur le calendrier pour la réalisation des travaux, en conformité au délai d'exécution contractuel, sous la forme d'un diagramme à barres montrant en particulier le chemin critique." },
          { label: "Essais de réception et mise en service", enabled: true, description: "Des renseignements détaillés sur le programme proposé de réalisation des essais de réception, et de mise en service des travaux achevés." },
          { label: "Autre exigence (selon le besoin)", enabled: false, description: "[insérer toute autre exigence, selon le besoin]" },
        ]
      },
    ],
  },
  {
    id: "surete",
    title: "Sûreté",
    icon: "🛡️",
    description: "Exigences sûreté pour zones à risque sécuritaire",
    fields: [
      { uid: "S07-INTRO", id: "surete_intro", label: "Note sur l'Insertion d'Exigences de Sûreté", type: "readonly", ref: "Notes à l'utilisateur",
        context: "Note d'introduction reprise du template DTAO Travaux PAY (page xvi). Cadre d'application des exigences sûreté dans les DAO financés par l'AFD.",
        notes: [
          "Dans des contextes de risque sécuritaire, l'AFD et le Maître d'Ouvrage doivent s'assurer que les Soumissionnaires évaluent correctement ce risque et prennent des mesures adaptées.\n\nConformément à l'Article 1.5.2 – Sûreté des Directives pour la Passation des Marchés financés par l'AFD dans les États étrangers, si le ou les lieux d'exécution des Travaux se situent dans une zone classée orange ou rouge par le ministère français de l'Europe et des affaires étrangères, le Maître d'Ouvrage devra inclure dans les Documents d'Appels d'Offres (DAO) des exigences relatives à la sûreté, incluant l'hypothèse d'une dégradation de la sûreté lors de l'exécution du Marché.\n\nPour ce faire, l'AFD a inséré dans ses DAO des exigences spécifiques, qui visent (i) à protéger des vies humaines sur les chantiers, (ii) à préserver sa réputation et celle de la Maîtrise d'Ouvrage, et (iii) à encourager les entreprises vertueuses à soumettre des Offres responsables.\n\nÀ cette fin, le présent DAO Travaux contient les exigences supplémentaires suivantes :\n• Des critères de qualification sûreté (paragraphe 6 du tableau des critères de qualification – Section III) ;\n• Une méthodologie sûreté à fournir par le Soumissionnaire (en conformité avec l'Article IS 11.1(i) des Données particulières de l'Appel d'Offres) ;\n• Un bordereau de prix unitaires sûreté identifiant les postes de prix sûreté payés dans le cadre du Marché (Tableau de prix - Section IV) ;\n• Des spécifications sûreté (Section VII) ;\n• Une nouvelle Sous-Clause 19.8 relative à la suspension ou la résiliation au titre de la sûreté du Personnel de l'Entrepreneur (Section IX).\n\nLa Maîtrise d'Ouvrage devra ajuster les spécifications sûreté en fonction de la nature du risque sécuritaire et en complétant les informations requises, en particulier sur les mesures de sûreté qu'elle prend à sa charge, et en sélectionnant les options pertinentes dans le texte.\n\nL'évaluation de chaque critère de qualification sûreté se fera sur la même base que les autres critères de qualification, à savoir « satisfait » ou « ne satisfait pas » à la condition requise.\n\nL'évaluation de la méthodologie sûreté consistera à déterminer si chaque condition de recevabilité spécifiée dans les spécifications sûreté est remplie. Dans le cas contraire, l'Offre sera rejetée.\n\nPendant l'exécution du Marché, une clause spécifique des conditions particulières a été ajoutée, afin de traiter une éventuelle détérioration des conditions sécuritaires qui conduirait à la démobilisation de l'entreprise."
        ] },
      { uid: "S07-001", id: "surete_applicable", label: "Zone orange/rouge MEAE", type: "select", options: ["Oui – inclure sûreté", "Non"], ref: "Spéc. Sûreté",
        context: "si le ou les lieux d'exécution des Travaux se situent dans une zone classée orange ou rouge par le ministère français de l'Europe et des affaires étrangères",
        note: "Classement MEAE." },
      { uid: "S07-002", id: "contexte_securitaire", label: "Description du contexte sécuritaire", type: "textarea", placeholder: "Événements récents, alertes des autorités locales / françaises / institutions internationales…", ref: "Spéc. Sûreté – Préambule", condition: "surete_applicable=Oui – inclure sûreté",
        context: "[Insérer une description du contexte sécuritaire et, en particulier, mentionner les événements récents pertinents et les alertes éventuellement émises par les autorités locales, françaises ou par des institutions internationales.]" },
      { uid: "S07-003", id: "roles_moa_surete", label: "Rôles et responsabilités du Maître d'Ouvrage", type: "textarea", placeholder: "Escorte, logements, gardiennage, transport, communication…", ref: "Spéc. Sûreté – Préambule", condition: "surete_applicable=Oui – inclure sûreté",
        context: "[Décrire les rôles et responsabilités, tâches et mise à disposition de moyens par le Maître d'Ouvrage pour assurer la sûreté des personnes et biens : escorte, logements, gardiennage, dispositions de transport, de communication, etc.]" },
      { uid: "S07-004", id: "roles_pilotage_surete_entreprise", label: "Pilotage sûreté entreprise principale (marchés par lots)", type: "textarea", placeholder: "Laisser vide si non pertinent — sinon préciser la répartition des rôles en cas de marchés par lots", ref: "Spéc. Sûreté – Préambule", condition: "surete_applicable=Oui – inclure sûreté",
        context: "[Il conviendra le cas échéant de préciser les rôles et responsabilités en matière de pilotage de la sûreté dévolus à l'entreprise principale, en cas de marchés par lots.]" },
      { uid: "S07-005", id: "conditions_tres_degradees", label: "Conditions sécuritaires très dégradées", type: "toggle", ref: "Spéc. Sûreté – 4.1 Organisation Sûreté", condition: "surete_applicable=Oui – inclure sûreté",
        context: "[Cocher l'Option N°1 en cas de contexte sécuritaire très dégradé ; sinon cocher l'Option N°2] — Option N°1 exige un Security Officer ET un prestataire sûreté ; Option N°2 exige l'un OU l'autre." },
      { uid: "S07-006", id: "escortes_non_prises_en_charge", label: "Escortes nécessaires non prises en charge par le MOA", type: "toggle", ref: "Spéc. Sûreté – 4.2 Déplacement", condition: "surete_applicable=Oui – inclure sûreté",
        context: "[à insérer en cas d'escortes jugées nécessaires et non prises en charge par le Maître d'Ouvrage ; sinon supprimer] Identification du prestataire chargé de mettre en œuvre les escortes." },
    ],
  },
  {
    id: "ccap",
    title: "CCAP – Données du Marché",
    icon: "📑",
    description: "Clauses administratives particulières – Partie A. La section commence par les noms/adresses MOA et MOE (repris automatiquement de la section « Informations générales »), puis le tableau « Résumé des Tranches », puis reprend les sous-clauses dans l'ordre du template Word.",
    fields: [
      // ── SC 1.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-001", id: "ccap_nom_adresse_moa", label: "Nom et adresse du Maître d'Ouvrage", type: "mirror", ref: "SC 1.1.2.2 & 1.3",
        mirrorFields: ["nom_maitrise_ouvrage", "adresse_moa"],
        context: "Ligne auto-remplie depuis PREA-004-a (nom) et PREA-004-a2 (adresse). Modifications à effectuer dans la section « Informations générales »." },
      { uid: "CCAP-002", id: "ccap_nom_adresse_moe", label: "Nom et adresse du Maître d'Œuvre", type: "mirror", ref: "SC 1.1.2.4 & 1.3",
        mirrorFields: ["nom_moe", "adresse_moe"],
        context: "Ligne auto-remplie depuis PREA-004b (nom) et PREA-004c (adresse). Modifications à effectuer dans la section « Informations générales »." },
      { uid: "CCAP-003", id: "tranches_marche_existe", label: "Le marché comporte des tranches ?", type: "toggle", ref: "CCAP 1.1.5.6",
        context: "Détermine si le tableau « Résumé des Tranches » est utilisé. Si « Non », le tableau est désactivé et plusieurs autres champs (Délai d'Achèvement, Pénalités de retard) basculent en saisie libre.",
        note: "Sélectionner « Oui » si le marché est scindé en plusieurs tranches (chacune avec son propre délai et ses pénalités). Sinon, choisir « Non »." },
      { uid: "CCAP-004", id: "tranches_table", label: "Résumé des Tranches", type: "tranchesTable", ref: "CCAP 1.1.5.6 / 1.1.3.3 / 8.7",
        disabledIf: "tranches_marche_existe=Non",
        context: "Tableau : Résumé des Tranches — Nom / Description des Tranches (Article 1.1.5.6) / Délai d'Achèvement (Article 1.1.3.3) / Pénalités de retard (Article 8.7).",
        note: "Ajoutez autant de tranches que nécessaire. Le tableau remplit automatiquement la section « Résumé des Tranches » du CCAP dans le document exporté." },
      { uid: "CCAP-005", id: "delai_achevement_ouvrages", label: "Délai d'Achèvement des Ouvrages", type: "text", placeholder: "Ex : 540 (en jours, ou « 18 mois »)", ref: "SC 1.1.3.3",
        context: "_________ jours. [Si des tranches sont utilisées, se référer au tableau ci-dessous : Résumé des Tranches.]",
        note: "Si CCAP-003 = Oui : saisir uniquement le nombre de jours (l'unité « jours. » est ajoutée automatiquement). Si CCAP-003 = Non : saisir un texte libre qui remplace toute la cellule (par exemple « 540 jours » ou « 18 mois »)." },
      { uid: "CCAP-006", id: "periode_garantie", label: "Période de Garantie (jours)", type: "text", placeholder: "365", ref: "SC 1.1.3.7",
        context: "365 jours. [Valeur par défaut du template FIDIC PAY ; à ajuster le cas échéant.]" },
      { uid: "CCAP-007", id: "tranches_ref_note", label: "Tranches — renvoi au tableau", type: "readonly", ref: "SC 1.1.5.6",
        context: "[Si des tranches sont utilisées, se référer au tableau ci-dessous : Résumé des Tranches.]",
        note: "Renseignez le tableau « Résumé des Tranches » en haut de cette section (CCAP-004). Le contenu de la sous-clause 1.1.5.6 est rempli automatiquement par ce tableau à l'export." },
      { uid: "CCAP-008", id: "specifications_esss_applicables_mirror", label: "Spécifications ESSS applicables", type: "mirror", ref: "SC 1.1.6.11",
        mirrorFields: ["esss_applicable"],
        context: "Valeur reprise automatiquement de S-ESSS-01 (section ESSS). Pour la modifier, se référer à la section ESSS.",
        note: "Cette indication n'apparaîtra pas dans le .docx exporté : seule la coche Oui/Non du CCAP §1.1.6.11 sera mise à jour selon la valeur de S-ESSS-01." },
      { uid: "CCAP-009", id: "conditions_climatiques_defavorables", label: "Conditions Climatiques Exceptionnellement Défavorables", type: "textarea", placeholder: "Ex : Pluie > 100 mm/24 h pendant 3 j consécutifs ; Vent > 80 km/h pendant 12 h ; Température > 45 °C pendant 5 j ; …", ref: "SC 1.1.6.15",
        context: "« Conditions Climatiques Exceptionnellement Défavorables » signifie : — La pluie : [indiquer l'intensité et la durée] ; — La vitesse du vent : [indiquer l'intensité et la durée] ; — La température : [indiquer l'intensité et la durée] ; — Etc. : [ajouter des éléments supplémentaires, le cas échéant].",
        note: "À définir pour chacun des sites de travaux. Un degré exceptionnel d'adversité correspond typiquement à une probabilité d'occurrence égale à 4–5 fois le Délai d'Achèvement (p. ex. une fois tous les 8–10 ans pour un marché de 2 ans)." },
      { uid: "CCAP-010", id: "droit_applicable", label: "Droit applicable", type: "text", placeholder: "Ex : Le droit de la République du Burkina Faso", ref: "SC 1.4",
        context: "Droit applicable au Marché : [insérer le droit]" },
      { uid: "CCAP-011", id: "langue_marche", label: "Langue du Marché", type: "text", placeholder: "Ex : Français", ref: "SC 1.4",
        context: "Langue du Marché : [insérer la langue]" },
      // ── SC 2.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-012", id: "delai_acces", label: "Délai d'accès au Chantier (jours)", type: "text", placeholder: "30", ref: "SC 2.1",
        context: "__________ jours après la Date de Commencement.",
        note: "Si plusieurs Tranches sont prévues et qu'un seul délai d'accès à toutes les zones n'est pas possible, indiquer ici les différents délais d'accès (un délai par Tranche au maximum est recommandé)." },
      // ── SC 3.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-013", id: "obligations_moe", label: "Obligations et Pouvoirs du Maître d'Œuvre", type: "multi_check_extensible", ref: "SC 3.1",
        context: "Le Maître d'Œuvre doit obtenir l'approbation spécifique du Maître d'Ouvrage avant d'entreprendre les actions suivantes. Cocher les actions à conserver ; les actions non cochées seront surlignées en rouge dans le .docx exporté.",
        note: "Cliquez sur l'icône ℹ️ à côté de chaque option pour afficher le texte intégral de la sous-clause concernée.",
        defaultOptions: [
          { id: "instr-changements", label: "Délivrer toute instruction causant des changements significatifs aux Ouvrages, ou une augmentation du Montant Accepté du Marché et/ou une prolongation du Délai d'Achèvement", subClauseRef: "Instruction de modification" },
          { id: "sc-3-5", label: "Procéder à une Détermination au titre de la Sous-Clause 3.5", subClauseRef: "Sous Clause 3.5 — Déterminations",
            subClauseText: "Lorsque ces Conditions prévoient que le Maître d'Œuvre doit procéder conformément à cette Sous Clause 3.5 pour parvenir à un accord sur ou déterminer toute question, le Maître d'Œuvre doit consulter chacune des Parties pour s'efforcer d'aboutir à un accord. Si un accord n'est pas obtenu, le Maître d'Œuvre effectuera une juste détermination conformément au Marché, en prenant en compte toutes les circonstances applicables.\n\nLe Maître d'Œuvre doit notifier les deux Parties de chaque accord ou détermination, précisions à l'appui, dans un délai de 28 jours à compter de la réception de la réclamation ou de la demande correspondante sauf si cela est spécifié autrement. Chaque Partie doit donner effet à chaque accord, ou détermination à moins et jusqu'à ce que révisée conformément à la Clause 20 [Réclamations, Différends et Arbitrage]." },
          { id: "sc-14-6", label: "Délivrer un Décompte Provisoire au titre de la Sous-Clause 14.6", subClauseRef: "Sous Clause 14.6 — Délivrance de Décomptes Intermédiaires",
            subClauseText: "Aucun montant ne sera certifié ou payé jusqu'à ce que le Maître d'Ouvrage ait reçu et approuvé la Garantie de Bonne Exécution. Ensuite, le Maître d'Œuvre doit, dans un délai de 28 jours après la réception d'une Demande de Décompte et des attachements justificatifs, délivrer au Maître d'Ouvrage et à l'Entrepreneur un Décompte Intermédiaire qui doit spécifier le montant que le Maître d'Œuvre détermine de manière juste être dû, ainsi, le cas échéant, que toutes précisions sur les déductions ou retenues effectuées par le Maître d'Œuvre sur la Demande de Décompte.\n\nToutefois, avant la délivrance du Certificat de Réception pour les Ouvrages, le Maître d'Œuvre ne sera pas tenu de délivrer un Décompte Intermédiaire d'un montant qui serait (après retenue et autres déductions) inférieur au montant minimum des Décomptes Intermédiaires mentionné (le cas échéant) dans les Données du Marché. Dans ce cas, le Maître d'Œuvre doit notifier l'Entrepreneur.\n\nLe traitement d'un Décompte Intermédiaire ne doit être suspendu pour aucune autre raison, cependant :\na) si une chose livrée ou des travaux effectués par l'Entrepreneur ne sont pas conformes au Marché, les coûts de la réparation ou du remplacement peuvent être retenus jusqu'à ce que la réparation ou le remplacement soit achevé ; et/ou\nb) si l'Entrepreneur manque ou a manqué à réaliser des travaux ou à satisfaire une obligation au titre du Marché, et qu'il en a été notifié par le Maître d'Œuvre, la valeur de ces travaux ou de cette obligation peut être retenue jusqu'à ce que les travaux ou l'obligation ait été exécutés.\n\nLe Maître d'Œuvre peut, dans un Décompte, procéder à toute correction ou modification qui devrait normalement être effectuée au titre de tout Décompte antérieur. Un Décompte ne doit pas être considéré comme constitutif de l'acceptation, de l'approbation, du consentement, ou de la satisfaction du Maître d'Œuvre." },
          { id: "sc-10-1-2", label: "Délivrer un Certificat de Réception au titre des Sous-Clauses 10.1 et 10.2", subClauseRef: "Sous Clauses 10.1 & 10.2 — Réception des Ouvrages",
            subClauseText: "10.1 — Réception des Ouvrages et des tranches : A l'exception de ce qui est mentionné à la Sous Clause 9.4 [Echec des Essais Préalables à la Réception], les Ouvrages seront réceptionnés par le Maître d'Ouvrage lorsque (i) les Ouvrages auront été achevés conformément au Marché, y compris les points visés à la Sous Clause 8.2 [Délai d'Achèvement] et à l'exception de ce qui est permis dans le paragraphe (a) ci-dessous, et (ii) le Certificat de Réception des Ouvrages aura été délivré ou sera considéré comme ayant été délivré conformément à cette Sous Clause.\n\nL'Entrepreneur peut, par notification au Maître d'Œuvre, demander un Certificat de Réception au plus tôt 14 jours avant que les Ouvrages ne soient, selon l'opinion de l'Entrepreneur, achevés et prêts à être réceptionnés. Si les Ouvrages sont scindés en Tranches, l'Entrepreneur pourra demander de la même manière un Certificat de Réception pour chaque Tranche.\n\nLe Maître d'Œuvre doit, dans un délai de 28 jours après la réception de la demande de l'Entrepreneur :\na) délivrer le Certificat de Réception à l'Entrepreneur, mentionnant la date à laquelle les Ouvrages ou la Tranche ont été achevés conformément au Marché, nonobstant des travaux mineurs restant à parachever et des désordres non susceptibles d'affecter substantiellement l'usage auquel les Ouvrages ou une Tranche sont destinés ; ou\nb) rejeter la demande, de façon motivée et en spécifiant les travaux que l'Entrepreneur doit exécuter pour que le Certificat de Réception soit délivré.\n\nSi le Maître d'Œuvre ne délivre pas de Certificat de Réception, ni ne rejette la demande de l'Entrepreneur dans ce délai de 28 jours, et si les Ouvrages ou la Tranche (selon le cas) sont substantiellement conformes au Marché, le Certificat de Réception sera réputé avoir été délivré le dernier jour de cette période.\n\n10.2 — Réception de parties des ouvrages : Le Maître d'Œuvre peut, à la seule discrétion du Maître d'Ouvrage, délivrer un Certificat de Réception pour toute partie des Ouvrages Définitifs. Le Maître d'Ouvrage ne doit utiliser aucune partie des Ouvrages tant que le Maître d'Œuvre n'a pas délivré un Certificat de Réception pour cette partie. Toutefois, si le Maître d'Ouvrage utilise une partie des Ouvrages avant que le Certificat de Réception ne soit délivré : (a) la partie qui est utilisée sera réputée avoir été réceptionnée à partir de la date à laquelle elle est utilisée, (b) l'Entrepreneur cessera d'être responsable de la garde d'une telle partie à partir de cette date, et (c) le Maître d'Œuvre, sur demande de l'Entrepreneur, devra délivrer un Certificat de Réception pour cette partie." },
        ] },
      // ── SC 4.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-014", id: "obligations_entrepreneur", label: "Obligations Générales de l'Entrepreneur", type: "multi_check_extensible", ref: "SC 4.1",
        context: "L'Entrepreneur doit fournir les documents suivants dans le cadre du Marché. Cocher les documents à conserver ; les documents non cochés seront surlignés en rouge dans le .docx exporté.",
        note: "Vous pouvez ajouter des documents supplémentaires en cliquant sur « + Ajouter une option ».",
        defaultOptions: [
          { id: "plans-execution", label: "Les plans d'exécution, qui doivent être approuvés par le Maître d'Œuvre avant que ne démarrent les travaux" },
          { id: "dossier-recolement", label: "Le dossier de récolement des ouvrages « tels que construits », qui doit être approuvé par le Maître d'Œuvre avant la réception des travaux" },
          { id: "manuels-exploitation", label: "Les manuels d'exploitation et de maintenance" },
        ] },
      { uid: "CCAP-015", id: "garantie_bonne_exec", label: "Garantie Bonne Exécution (%)", type: "text", placeholder: "5-10%", ref: "SC 4.2",
        context: "La Garantie de Bonne Exécution doit être sous la forme d'une garantie bancaire pour le(s) montant(s) de [indiquer un chiffre entre 5 et 10] pour cent du Montant Accepté du Marché" },
      { uid: "CCAP-016", id: "sous_traitants_paiement_direct", label: "Sous-Traitants — paiement direct autorisé ?", type: "select", options: ["Oui", "Non"], ref: "SC 4.4",
        context: "Paiement direct des Sous-Traitants autorisé : oui/non [rayer la mention inutile]",
        note: "Le paiement direct par le Maître d'Ouvrage des prestations exécutées par les Sous-Traitants permet à ces derniers d'avoir la certitude d'être payés. Si « Oui », des dispositions complémentaires (SC 14.6) s'appliquent." },
      { uid: "CCAP-017", id: "frequence_rapports_avancement", label: "Fréquence des rapports d'avancement", type: "text", placeholder: "Ex : mensuelle, bimensuelle, trimestrielle…", ref: "SC 4.21",
        context: "Fréquence des rapports d'avancement : [Insérer la fréquence seulement si elle n'est pas mensuelle ; sinon, supprimer.]",
        note: "Laisser vide si la fréquence est mensuelle (valeur par défaut)." },
      // ── SC 6.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-018", id: "heures_travail", label: "Heures de travail", type: "text", placeholder: "Ex : 7h-18h Lun-Sam", ref: "SC 6.5",
        context: "__________ [Indiquer les heures normales de travail.]" },
      // ── SC 8.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-019", id: "date_commencement", label: "Date de Commencement", type: "text", placeholder: "Ex : Signature de l'Acte d'Engagement", ref: "SC 8.1",
        context: "La Date de Commencement doit être : [Insérer la liste des conditions telles que spécifiées dans la SousClause 8.1 des CCAG, ou une date, ou la date de signature de l'Acte d'Engagement (sujette à la fourniture par l'Entrepreneur d'une Garantie de Bonne Exécution).]" },
      { uid: "CCAP-020", id: "penalites_retard_ouvrages", label: "Pénalités de retard pour les Ouvrages", type: "text", placeholder: "Ex : 1 (en pour mille du Montant du Marché par jour)", ref: "SC 8.7 & 14.15(b)",
        context: "[Généralement d'environ un pour mille 1‰] % du Montant du Marché par jour. [Si des Tranches sont utilisées, se référer au Tableau « Résumé des Tranches » ci-dessous.]",
        note: "Si CCAP-003 = Oui (tranches utilisées) : le champ est rempli automatiquement avec le renvoi au tableau « Résumé des Tranches » et n'est pas modifiable. Si CCAP-003 = Non : saisir la valeur en pour mille (‰) du Montant du Marché par jour.",
        lockedIf: { condition: "tranches_marche_existe=Oui", value: "Se référer au tableau « Résumé des Tranches » ci-dessous." } },
      { uid: "CCAP-021", id: "penalites_max", label: "Pénalités de retard – plafond (%)", type: "text", placeholder: "≤ 10 %", ref: "SC 8.7",
        context: "Montant maximum des pénalités de retard : [Insérer un pourcentage ne dépassant pas 10] % du Montant final du Marché." },
      // ── SC 13.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-022", id: "pourcentage_provisions", label: "Pourcentage pour l'ajustement des Sommes provisionnelles (%)", type: "text", placeholder: "Ex : 5", ref: "SC 13.5(b)(ii)",
        naToggle: true,
        context: "_______ [5] % — [S'il y a des Sommes provisionnelles, insérer un pourcentage pour les frais généraux et la marge].",
        note: "Sous-clauses du CCAG concernées (PAY 2024) :\n\n• 1.1.4.10 — « Provisions » (également appelée somme provisionnelle) désigne le ou les montant(s) (le cas échéant) défini(s) dans le Marché comme constituant une provision pour la réalisation de toute partie des Ouvrages ou pour la fourniture des Equipements, des Matériaux ou des services, en application de la Sous-Clause 13.5 [Provisions].\n\n• 13.5 — Provisions : chacune des Provisions ne doit être utilisée, en tout ou partie, que conformément aux instructions du Maître d'Œuvre, et le Montant du Marché doit être ajusté en conséquence. La somme totale payée à l'Entrepreneur ne doit inclure que les montants pour les travaux, les fournitures ou les services liés aux Provisions, tels qu'ordonnés par le Maître d'Œuvre. Pour chaque Provision, le Maître d'Œuvre peut ordonner :\n  a) le travail à exécuter (y compris les Equipements, les Matériaux ou les services à fournir) par l'Entrepreneur et valorisé selon les dispositions de la Sous-Clause 13.3 [Procédure de Changement] ; et/ou\n  b) les Equipements, les Matériaux ou les services à acheter par l'Entrepreneur auprès d'un Sous-Traitant désigné (tel que visé à la Clause 5 [Sous-Traitants désignés]) ou auprès d'une autre source, et pour lesquels doivent être intégrés au Montant du Marché :\n    (i) les montants réels payés (ou à payer) par l'Entrepreneur, et\n    (ii) une somme pour les frais généraux et le profit, calculée comme étant un pourcentage de ces montants réels en utilisant le pourcentage applicable (le cas échéant) tel que spécifié dans le Bordereau concerné. Si aucun taux n'y est mentionné, le pourcentage spécifié dans les Données du Marché doit être utilisé.\n\nL'Entrepreneur doit, quand le Maître d'Œuvre l'exige, présenter, à titre de justificatifs, devis, factures, quittances et relevés de comptes ou reçus.\n\nCliquer sur « N/A » si le Marché ne comporte pas de Sommes provisionnelles : la cellule sera remplacée par « Non applicable »." },
      // ── SC 14.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-023", id: "montant_marche_type", label: "Type de Marché", type: "select", options: ["Prix Global et Forfaitaire", "Prix Unitaires", "Combinaison Forfaitaire + Unitaires"], ref: "SC 14.1",
        context: "[Choisir l'option correspondant au Marché parmi les suivantes :]\n• Le marché est à Prix Global et Forfaitaire\n• Le Marché est à Prix Unitaires\n• Le Marché est une combinaison d'une Composante à Prix Global et Forfaitaire et d'une Composante à Prix Unitaires.",
        note: "Les options non retenues seront automatiquement surlignées en rouge dans le .docx exporté (l'option choisie reste en clair). Si « Combinaison… » est sélectionnée, deux champs supplémentaires apparaissent pour décrire chaque composante." },
      { uid: "CCAP-024", id: "description_composante_forfaitaire", label: "Composante à Prix Global et Forfaitaire — description", type: "textarea", ref: "SC 14.1",
        condition: "montant_marche_type=Combinaison Forfaitaire + Unitaires",
        context: "La Composante à Prix Global et Forfaitaire consiste en : [insérer une courte description de la nature de la composante et/ou faire référence aux Spécifications et aux Bordereaux]",
        note: "À remplir uniquement si CCAP-023 = « Combinaison Forfaitaire + Unitaires ». Le texte saisi remplace le placeholder jaune correspondant dans le .docx." },
      { uid: "CCAP-025", id: "description_composante_unitaire", label: "Composante à Prix Unitaires — description", type: "textarea", ref: "SC 14.1",
        condition: "montant_marche_type=Combinaison Forfaitaire + Unitaires",
        context: "La Composante à Prix Unitaires consiste en : [insérer une courte description de la nature de la composante et/ou faire référence aux Spécifications et aux Bordereaux.]",
        note: "À remplir uniquement si CCAP-023 = « Combinaison Forfaitaire + Unitaires ». Le texte saisi remplace le placeholder jaune correspondant dans le .docx." },
      { uid: "CCAP-026", id: "droits_taxes_exemptions", label: "Droits, taxes et impôts — exemptions à insérer", type: "textarea", ref: "SC 14.1(b)",
        placeholder: "Ex : TVA sur les fournitures locales ; droits à l'importation sur les Equipements ; …",
        context: "Les exemptions de droits, de taxes et d'impôts suivantes s'appliquent au Marché : [Si applicable, insérer les exemptions (par exemple TVA, droits à l'importation) en cohérence avec l'IS 14.7].",
        note: "Lister chaque exemption sur une ligne. Le texte saisi remplace le placeholder jaune dans le .docx." },
      { uid: "CCAP-027", id: "droits_taxes_alinea_e", label: "Droits, taxes et impôts — alinéa (e) applicable ?", type: "select", options: ["Oui", "Non"], ref: "SC 14.1(e)",
        context: "Le nouvel alinéa (e) figurant dans la Partie B du CCAP sur l'exemption des droits et taxes d'importation est applicable : Oui / Non [Supprimer la mention inutile].",
        note: "Si « Oui » : le matériel et les pièces détachées importés par l'Entrepreneur pour l'exécution du Marché bénéficient d'une exemption douanière temporaire (Partie B du CCAP). Si « Non » : la mention « Oui » sera surlignée rouge à l'export.\n\n— Texte intégral de l'alinéa (e) (Partie B du CCAP) —\n\n« Nonobstant les dispositions de l'alinéa (b), le Matériel de l'Entrepreneur, incluant ses pièces détachées essentielles, importées par l'Entrepreneur dans le but unique d'exécuter le Marché, sera temporairement exempté du paiement des droits et taxes d'importation pour l'importation initiale, sous réserve que l'Entrepreneur puisse apporter aux autorités douanières du port d'entrée une garantie bancaire, valide 6 mois après le Délai d'Achèvement, pour un montant égal au total des droits et taxes d'importation qui serait payable sur la valeur d'importation évaluée d'un tel Matériel de l'Entrepreneur et de ses pièces détachées et qui serait exigible dans le cas où le Matériel de l'Entrepreneur ne serait pas exporté du Pays à l'achèvement du Marché. Une copie de la garantie bancaire visée par les autorités douanières doit être fournie par l'Entrepreneur au Maître d'Ouvrage lors de l'importation des Articles individuels du Matériel de l'Entrepreneur et de ses pièces détachées.\n\nLors de l'exportation des Articles individuels du Matériel de l'Entrepreneur ou de ses pièces détachées ou à l'achèvement du Marché, l'Entrepreneur doit préparer, pour approbation par les autorités douanières, une évaluation de la valeur résiduelle du Matériel de l'Entrepreneur et de ses pièces détachées à exporter, basée sur l'échelle de dépréciation ou autre critère utilisés par les autorités douanières pour un tel but en conformité avec les dispositions des Lois applicables. Les droits et taxes d'importation sont dus et payables aux autorités douanières par l'Entrepreneur sur (a) la différence entre la valeur initiale d'importation et la valeur résiduelle du Matériel de l'Entrepreneur et de ses pièces détachées à exporter et (b) sur la valeur initiale importée du Matériel de l'Entrepreneur et de ses pièces détachées restant dans le Pays après l'achèvement du Marché. Lors du paiement de telles sommes dues dans les 28 jours après leur facturation, la garantie bancaire sera réduite ou libérée en conséquence ; sinon la garantie sera appelée à hauteur du montant total restant. »" },
      { uid: "CCAP-028", id: "avance_demarrage", label: "Avance de Démarrage (%)", type: "text", placeholder: "10-20 %", ref: "SC 14.2",
        context: "______ % du Montant Accepté du Marché [Insérer un nombre entre 10 et 20]" },
      { uid: "CCAP-029", id: "retenue_garantie", label: "Pourcentage de la Retenue (%)", type: "text", placeholder: "5-10 %", ref: "SC 14.3",
        context: "[Insérer un pourcentage de retenue entre 5 et 10] %" },
      { uid: "CCAP-030", id: "plafond_retenue", label: "Plafond de la Retenue de Garantie (%)", type: "text", placeholder: "GBE + retenue ≤ 15 %", ref: "SC 14.3",
        context: "______ % du Montant Accepté du Marché [le cumul de la Garantie de Bonne Exécution et de la Retenue de Garantie ne doit pas dépasser 15%]" },
      { uid: "CCAP-031", id: "equipements_materiaux_applique", label: "La Sous-Clause 14.5 (Equipements et Matériaux) s'applique ?", type: "toggle", ref: "SC 14.5",
        context: "Equipements et Matériaux destinés aux Ouvrages — [Si la Sous-Clause 14.5 s'applique :].",
        note: "Si « Non » : tout le bloc Equipements et Matériaux (paiement FOB et livraison sur Chantier) sera surligné rouge dans le .docx. Si « Oui » : remplir les deux listes ci-dessous.\n\n— Texte intégral de la Sous-Clause 14.5 (Equipements et Matériaux destinés aux Ouvrages) —\n\nS'il est fait application des dispositions de la présente Sous-Clause, les Décomptes Intermédiaires doivent inclure, au titre du paragraphe (e) de la Sous-Clause 14.3 [Demande de Décomptes Intermédiaires], (i) un montant pour les Equipements et les Matériaux qui ont été envoyés sur le Chantier pour incorporation aux Ouvrages Définitifs, et (ii) une réfaction lorsque la valeur contractuelle de ces Equipements et des Matériaux est incluse au titre des Ouvrages Définitifs dans le paragraphe (a) de la Sous-Clause 14.3 [Demande de Décomptes Intermédiaires].\n\nSi les éléments énumérés aux paragraphes (b)(i) ou (c)(i) ci-dessous ne sont pas inclus dans les Bordereaux, cette Sous-Clause ne sera pas applicable.\n\nLe Maître d'Œuvre doit déterminer et certifier chaque montant additionnel si les conditions suivantes sont réunies :\n\na) l'Entrepreneur a :\n   (i) conservé des enregistrements acceptables (incluant des commandes, des reçus, les Coûts et l'utilisation des Equipements et Matériaux) qui sont mis à disposition pour inspection, et\n   (ii) soumis un décompte du Coût d'acquisition et de livraison des Equipements et des Matériaux sur le Chantier accompagné de justificatifs acceptables ;\n\net, soit :\n\nb) les Equipements et Matériaux concernés :\n   (i) sont ceux mentionnés dans les Bordereaux pour le paiement lorsqu'ils ont été expédiés,\n   (ii) ont été expédiés vers le Pays, sont en route vers le Chantier, conformément au Marché ; et\n   sont décrits dans un connaissement de transport sans réserve ou autre justificatif d'expédition, lequel a été fourni au Maître d'Œuvre assorti du justificatif du paiement du fret et de l'assurance, de tout autre document raisonnablement exigible, et d'une garantie bancaire, délivrée selon un modèle et par une entité approuvés par le Maître d'Ouvrage, de montants et dans les devises égaux au montant dû en vertu de cette Sous-Clause : cette garantie peut être délivrée selon un modèle similaire à celui auquel il est fait référence dans la Sous-Clause 14.2 [Paiement de l'Avance de Démarrage] et doit être valable jusqu'à ce que les Equipements et les Matériaux soient convenablement stockés sur le Chantier et protégés contre toute perte, dommage ou détérioration ;\n\nsoit :\n\nc) les Equipements et Matériaux concernés :\n   (i) sont ceux mentionnés dans les Bordereaux pour paiement lorsqu'ils sont livrés sur le Chantier, et\n   (ii) ont été livrés et convenablement stockés sur le Chantier, et sont protégés contre toute perte, dommage ou détérioration, et paraissent être conformes au Marché.\n\nLe montant additionnel à certifier sera l'équivalent de quatre-vingts pour cent (80 %) du montant déterminé par le Maître d'Œuvre pour le coût des Equipements et des Matériaux (y compris de livraison sur le Chantier), en tenant compte des documents visés à cette Sous-Clause et de la valeur au Marché de ces Equipements et Matériaux.\n\nLes devises pour ce montant additionnel doivent être les mêmes que celles dans lesquelles le paiement sera dû lorsque leur valeur contractuelle sera prise en compte au titre du paragraphe (a) de la Sous-Clause 14.3 [Demande de Décomptes Intermédiaires]. A ce moment-là, le Décompte devra inclure la déduction applicable qui doit être équivalente au, et dans les mêmes devises et proportions que le montant additionnel pour les Equipements et les Matériaux concernés." },
      { uid: "CCAP-032", id: "equipements_materiaux_fob", label: "Equipements et Matériaux pour paiement FOB (Free on Board)", type: "textarea", ref: "SC 14.5(b)(i)",
        condition: "equipements_materiaux_applique=Oui",
        placeholder: "Ex : turbines hydrauliques ; transformateurs MT/BT ; …",
        context: "Equipements et Matériaux pour paiement FOB (Free on Board) [liste].",
        note: "Lister un Equipement / Matériau par ligne." },
      { uid: "CCAP-033", id: "equipements_materiaux_chantier", label: "Equipements et Matériaux pour paiement lorsque livrés sur le Chantier", type: "textarea", ref: "SC 14.5(c)(i)",
        condition: "equipements_materiaux_applique=Oui",
        placeholder: "Ex : poteaux béton ; câbles ; …",
        context: "Equipements et Matériaux pour paiement lorsque livrés sur le Chantier [liste].",
        note: "Lister un Equipement / Matériau par ligne." },
      { uid: "CCAP-034", id: "montant_min_decompte", label: "Montant minimum des Décomptes Intermédiaires", type: "text", placeholder: "Ex : 10 000 EUR", ref: "SC 14.6",
        context: "[Insérer un montant, 10.000 EUR par exemple]" },
      { uid: "CCAP-035", id: "delai_paiement", label: "Délai de paiement (jours)", type: "text", placeholder: "56", ref: "SC 14.7",
        context: "le Maître d'Ouvrage doit payer à l'Entrepreneur le montant certifié dans un délai de _______ [insérer un nombre s'il est différent de 56] jours." },
      { uid: "CCAP-036", id: "taux_interet_etrangere", label: "Sources de publication des taux d'intérêts (monnaie étrangère)", type: "text", ref: "SC 14.8",
        placeholder: "Ex : EURIBOR + 200 pb",
        context: "Le taux d'intérêts pour les paiements en monnaie locale est celui de la Sous-Clause 14.8 du CCAG. Le taux d'intérêts pour les paiements en monnaie étrangère est [insérer EURIBOR + 200 pb].",
        note: "Indiquer la source et la marge applicables aux paiements en monnaie étrangère (ex. « EURIBOR 6 mois + 200 pb »). Le texte saisi remplace le placeholder jaune dans le .docx." },
      // ── SC 17.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-037", id: "multiplicateur_responsabilite", label: "Multiplicateur de la limitation de la responsabilité", type: "text", ref: "SC 17.6",
        placeholder: "Ex : 1, 1.5, 2, 3",
        context: "La responsabilité totale de l'Entrepreneur envers le Maître d'Ouvrage ne doit pas excéder le Montant Accepté du Marché, multiplié par _______ [insérer un multiplicateur égal ou supérieur à un, n'excédant pas trois].",
        note: "Saisir un nombre ≥ 1 et ≤ 3. Le texte saisi remplace le placeholder jaune dans le .docx (les underscores qui précèdent sont automatiquement nettoyés)." },
      // ── SC 18.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-038", id: "delai_assurance_attestation", label: "Délai attestation d'assurance (jours)", type: "text", placeholder: "14-28", ref: "SC 18.1",
        context: "Délais de présentation des assurances : a) Attestation d'assurance : __________ jours.",
        note: "Ce délai peut être de 14 à 28 jours." },
      { uid: "CCAP-039", id: "delai_assurance_police", label: "Délai polices d'assurance applicables (jours)", type: "text", placeholder: "14-28", ref: "SC 18.1",
        context: "Délais de présentation des assurances : b) Polices d'assurance applicables : __________ jours.",
        note: "Ce délai peut être de 14 à 28 jours." },
      { uid: "CCAP-040", id: "assurance_montant_min", label: "Minimum assurance atteintes biens/personnes", type: "text", placeholder: "Montant par sinistre", ref: "SC 18.3",
        context: "Montant minimum de l'assurance contre les atteintes aux biens et aux personnes, par sinistre : __________ [Insérer le montant].",
        note: "Indiquer le montant minimum par sinistre (devise du Marché ou EUR). Les underscores qui précèdent dans le .docx sont automatiquement nettoyés." },
      // ── SC 20.x ─────────────────────────────────────────────────────────
      { uid: "CCAP-041", id: "crd_composition", label: "Le CRD doit comprendre", type: "select", options: ["un membre unique", "Trois membres"], ref: "SC 20.2",
        context: "Le CRD doit comprendre : [Soit :] un membre unique [soit :] Trois membres.",
        note: "« un membre unique » : le champ « Liste de membres potentiels » ci-dessous doit être renseigné. « Trois membres » : le champ « Liste de membres potentiels » est automatiquement rempli avec « aucun »." },
      { uid: "CCAP-042", id: "crd_liste", label: "Liste de membres potentiels du CRD", type: "text", placeholder: "Liste si CRD à un membre unique ; sinon « aucun »", ref: "SC 20.2",
        context: "[Insérer la(les) liste(s) de membres potentiels, uniquement lorsque le CRD comprend un membre unique ; sinon, insérer \"aucun\".]",
        lockedIf: { condition: "crd_composition=Trois membres", value: "aucun" } },
      { uid: "CCAP-043", id: "nomination_crd", label: "Nomination du CRD par (à défaut d'accord)", type: "text", placeholder: "Ex : Président du FIDIC", ref: "SC 20.3",
        context: "[Insérer le nom de la personne officielle ou de l'entité procédant à la désignation, i.e. Président du FIDIC ou une autre association régionale d'ingénieurs.]" },
      { uid: "CCAP-044", id: "institution_arbitrage", label: "Institution d'arbitrage", type: "text", placeholder: "CCI par défaut", ref: "SC 20.6",
        context: "[Insérer le nom de l'institution arbitrale si elle est différente de la Chambre de Commerce Internationale.]" },
      { uid: "CCAP-045", id: "lieu_arbitrage", label: "Lieu d'arbitrage", type: "text", placeholder: "Lieu neutre", ref: "SC 20.6",
        context: "[Insérer le lieu de l'arbitrage : il doit être neutre, c'est-à-dire être ni le pays du Maître d'Ouvrage ni le pays du siège de l'Entrepreneur.]" },
    ],
  },
];

